### ISSUE TITLE
Outdated report

### ISSUE THREAD

**Issue by krishnakantsingh14** [alexandrovteam/pyimzML#12]
Report.pdf is outdated. Functions, such as getionimage(), do not work in same way as written in report.pdf.

**Comment by sergii-mamedov** [comment]
As you can see, Report.pdf was created in 2015 and reflects the state of the `pyimzml` module at that time. Of course, a lot has changed in pyimzml in recent years. Current documentation is available on [this page](https://pyimzml.readthedocs.io/en/latest/).
