### ISSUE TITLE
MUST supply term of IMS:1000101 (external data)

### ISSUE THREAD

**Issue by paoloinglese** [alexandrovteam/pyimzML#17]
Missing term IMS:1000101 in the path mzML/run/spectrumList/spectrum/binaryDataArrayList/binaryDataArray

**Comment by intsco** [comment]
@paoloinglese would you mind providing the full stack trace of the exception?

**Comment by paoloinglese** [comment]
Hi @intsco, following the 1.1.0 RC1

https://ms-imaging.org/wp/wp-content/uploads/2009/08/specifications_imzML1.1.0_RC1.pdf

the path should have that field (see page 12 of the pdf).

**Comment by intsco** [comment]
Resolved by #18
