### ISSUE TITLE
could not install the library

### ISSUE THREAD

**Issue by hzxxxxxx** [alexandrovteam/pyimzML#20]
I tried various installation methods, but they all failed to install. When installing using pip, I would get stuck in the using cache step. Downloading the package for local installation would also stay at the processing step.
![E%1Y8U7P913QX@P{LSL1KTH](https://user-images.githubusercontent.com/52093790/83713407-9678fb80-a65a-11ea-9d4d-c496c3c4b6ad.png)

**Comment by intsco** [comment]
The standard installation seems to be working
```
(pyimzml) C:\Users\username>pip install pyimzml
Collecting pyimzml
  Using cached pyimzML-1.3.0.tar.gz (13 kB)
Collecting numpy
  Downloading numpy-1.18.5-cp36-cp36m-win_amd64.whl (12.7 MB)
     |████████████████████████████████| 12.7 MB 6.4 MB/s
Collecting wheezy.template
  Using cached wheezy.template-0.1.167.tar.gz (15 kB)
Building wheels for collected packages: pyimzml, wheezy.template
  Building wheel for pyimzml (setup.py) ... done
  Created wheel for pyimzml: filename=pyimzML-1.3.0-py3-none-any.whl size=13988 sha256=c1fa7ffe7ae0882356e4663ec07fab3fe64365166142a8379b07b2ce3e977977
  Stored in directory: c:\users\rappez\appdata\local\pip\cache\wheels\a5\ef\64\9739cc80349766bfd22b1485d2289392e0d886b8109bec5ac1
  Building wheel for wheezy.template (setup.py) ... done
  Created wheel for wheezy.template: filename=wheezy.template-0.1.167-py3-none-any.whl size=19185 sha256=3d0c0e7d49fc1da7825da82c78e8cdd3fb76cfb1864fc51f1a76b155533bea94
  Stored in directory: c:\users\rappez\appdata\local\pip\cache\wheels\14\9e\4c\f235ac00a0b6e3976724ffc1e195a07917a9a5ad0ea5a5bcf3
Successfully built pyimzml wheezy.template
Installing collected packages: numpy, wheezy.template, pyimzml
Successfully installed numpy-1.18.5 pyimzml-1.3.0 wheezy.template-0.1.167
```

Could you post the command you use to install `pyimzml` and the full installation log?

**Comment by paoloinglese** [comment]
Could you try with easy_install?

`easy_install pyimzml`

You may need to install the Visual c++ redistributable, before.

**Comment by LachlanStuart** [comment]
I finally found the cause. Cython (used by wheezy.template during build) has an [infinite loop issue on Windows](https://github.com/cython/cython/issues/3262). 

A workaround is to uninstall Cython during installation then reinstall it afterwards. First run `pip list` to find your current Cython version, then:
```
pip uninstall Cython
pip install pyimzml
pip install Cython==<the version from pip list>
```
