### ISSUE TITLE
could not run ImzMLParser correctly

### ISSUE THREAD

**Issue by hanghu1024** [alexandrovteam/pyimzML#26]
When I run the ImzMLParser to parse a .imzML dataset from METASPACE, I get the error message: list index out of range. The full error message is attached below, could you help on it? Thanks!
```
~\Anaconda3\lib\site-packages\pyimzml\ImzMLParser.py in __init__(self, filename, parse_lib, ibd_file, include_spectra_metadata)
    133         if ibd_file is INFER_IBD_FROM_IMZML:
    134             # name of the binary file
--> 135             ibd_filename = self._infer_bin_filename(self.filename)
    136             self.m = open(ibd_filename, "rb")
    137         else:

~\Anaconda3\lib\site-packages\pyimzml\ImzMLParser.py in _infer_bin_filename(imzml_path)
    147         imzml_path = Path(imzml_path)
    148         ibd_path = [f for f in imzml_path.parent.glob('*')
--> 149                     if re.match(r'.+\.ibd', str(f), re.IGNORECASE) and f.stem == imzml_path.stem][0]
    150         return str(ibd_path)
    151 

IndexError: list index out of range
```

**Comment by hanghu1024** [comment]
After reading https://ms-imaging.org/wp/imzml/data-structure/, realize it works with .imzML and .ibd files together.

**Comment by LachlanStuart** [comment]
Hi @hanghu1024 ,

The `.imzML` file contains metadata, and the `.ibd` file contains spectrum data. You need both files for most tasks. 

If you only want metadata and don't need spectrum data, you can specify `ibd_file=None` when calling `ImzMLParser()` and it won't try to open the `.ibd` file, however this means that spectrum functions such as `.getspectrum` will fail.

It sounds like you've found the solution to this, so I'll close this issue. If you have any further questions, feel free to comment, reopen it or create a new issue.

**Comment by hanghu1024** [comment]
Great! That's good to know! This package is great, more detailed documentation would make it better.
