### ISSUE TITLE
Issue reading some imzML files

### ISSUE THREAD

**Issue by aryre** [alexandrovteam/pyimzML#33]
I am trying to read an imzML file using this fuction:

def getspectrum(self, index):
        mz_bytes, intensity_bytes = self.get_spectrum_as_string(index)
        mz_array = np.frombuffer(mz_bytes, dtype=self.mzPrecision)
        intensity_array = np.frombuffer(intensity_bytes, dtype=self.intensityPrecision)
        return mz_array, intensity_array

I get this error:
       ValueError: buffer size must be a multiple of element size

The pixel that is not able to read has different lengths for mz and intensities, i.e.  len(mz_bytes) > len(intensity_bytes)

**Comment by theodev** [comment]
Hi @aryre, it seems like you described the problem correctly and our error message was informative, that your .ibd file is corrupted, and that the spectrum has more intensity values than m/z values.

**Comment by theodev** [comment]
@aryre before you try fixing the issue I'd suggest to look into the problem and narrow it down, why do you have the different numbers of the m/z values and intensities?
