### ISSUE TITLE
error while opening the imzml file made by firefly software from Prosolia Inc,

### ISSUE THREAD

**Issue by Kumarsan201006** [alexandrovteam/pyimzML#37]
cannot able to open a DESI imzml file made by firefly software from prosolia inc. 

I get the following errors.

p = ImzMLParser("C:\\Users\\Thermo\\Downloads\\pyimzml\\data\\firelfy\\Org_3_11_.imzML")
Traceback (most recent call last):

  Input In [9] in <cell line: 1>
    p = ImzMLParser("C:\\Users\\Thermo\\Downloads\\pyimzml\\data\\firelfy\\Org_3_11_.imzML")

  File ~\anaconda3\lib\site-packages\pyimzml\ImzMLParser.py:140 in __init__
    self.imzmldict = self.__readimzmlmeta()

  File ~\anaconda3\lib\site-packages\pyimzml\ImzMLParser.py:319 in __readimzmlmeta
    val = _get_cv_param(scan_settings_list_elem, accession, deep=True, convert=True)

  File ~\anaconda3\lib\site-packages\pyimzml\ImzMLParser.py:50 in _get_cv_param
    node = elem.find('%s%scvParam[@accession="%s"]' % (base, XMLNS_PREFIX, accession))

AttributeError: 'NoneType' object has no attribute 'find'

**Comment by sergii-mamedov** [comment]
I saw your datasets with this error on METASPACE. The problem is an invalid imzML file.

The first two lines in the imzML file should look like this:
```
<?xml version="1.0"?>
<mzML xmlns="http://psi.hupo.org/ms/mzml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.0_idx.xsd" version="1.1">
```

Your file is missing the first line and `xmlns` has the wrong URL:
```
<mzML xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

Most likely, the problem is in the converter or its settings.
